"""Domain Models for Forex Learning, Post-Trade Reflection & Lesson Retrieval (Phase 17).

Provides strongly-typed models for:
- ForexLesson: Granular, prescriptive heuristic derived from post-trade analysis.
- ReflectionRating & TradeReflection: Structured evaluation of trade execution discipline.
- RetrievedLesson: Lesson ranked by relevance score for dynamic prompt augmentation.
- ReflectionContext: Comprehensive context bundle supplied to the reflection agent.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from tradingagents.agents.schemas_forex import ForexTraderProposal
from tradingagents.database.models import (
    OrderExecutionRecord,
    ProposalRecord,
    TradeJournalRecord,
)
from tradingagents.journal.models import TradeEvent
from tradingagents.metrics.models import (
    ExecutionQuality,
    TradeMfeMae,
    TradeOutcomeResult,
)


class ReflectionRating(str, Enum):
    """Overall execution quality and behavioral grade for a trade."""

    EXCELLENT = "EXCELLENT"            # Exemplary adherence to strategy, optimal exit
    GOOD = "GOOD"                      # Controlled execution with solid risk containment
    NEUTRAL = "NEUTRAL"                # Scratch or routine trade with minimal learning signal
    POOR = "POOR"                      # Execution errors, greedy reversal, or premature exit
    CRITICAL_ERROR = "CRITICAL_ERROR"  # Hard rule breach, stop loss violation, or runaway loss


class ForexLesson(BaseModel):
    """Institutional heuristic or rule extracted from post-trade reflection."""

    lesson_id: str = Field(default_factory=lambda: f"lsn_{uuid.uuid4().hex[:12]}")
    trade_id: str | None = None
    proposal_id: str | None = None
    pair: str
    setup_type: str = "TREND_CONTINUATION"
    outcome_category: str = "STANDARD_WIN"
    rule_violated: str | None = None
    observation: str = ""
    root_cause: str = ""
    actionable_rule: str = ""
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0)
    tags: list[str] = Field(default_factory=list)
    created_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class RetrievedLesson(BaseModel):
    """A lesson retrieved from memory with an attached relevance score and diagnostic match reasons."""

    lesson: ForexLesson
    relevance_score: float = Field(default=1.0, ge=0.0, le=1.0)
    match_reasons: list[str] = Field(default_factory=list)


class TradeReflection(BaseModel):
    """Structured post-trade reflection report generated by ForexReflectionAgent (Phase 14)."""

    trade_id: str
    rating: ReflectionRating = ReflectionRating.NEUTRAL

    # Structured evaluation dimensions (Phase 14)
    thesis_quality: str = "GOOD"
    direction_quality: str = "GOOD"
    entry_quality: str = "GOOD"
    stop_quality: str = "GOOD"
    target_quality: str = "GOOD"
    execution_quality: str = "GOOD"
    management_quality: str = "GOOD"
    main_success: str = ""
    main_failure: str = ""

    summary: str = ""
    what_went_well: list[str] = Field(default_factory=list)
    what_went_wrong: list[str] = Field(default_factory=list)
    lessons: list[ForexLesson] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    generated_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class ReflectionContext(BaseModel):
    """Full operational context bundle supplied to the reflection engine (Phase 14)."""

    trade: TradeJournalRecord
    proposal: ProposalRecord | ForexTraderProposal | None = None
    mfe_mae: TradeMfeMae | None = None
    outcome: TradeOutcomeResult | None = None
    executions: list[OrderExecutionRecord | ExecutionQuality] = Field(default_factory=list)
    events: list[TradeEvent] = Field(default_factory=list)

    # Detailed operational dimensions (Phase 14)
    risk_decision: dict[str, Any] | None = None
    execution_quality: Any | None = None
    session: str | None = None
    setup: str | None = None
    market_news_context: dict[str, Any] = Field(default_factory=dict)

    @property
    def original_proposal(self) -> ProposalRecord | ForexTraderProposal | None:
        """Alias for proposal record."""
        return self.proposal

    @property
    def actual_fills(self) -> list[OrderExecutionRecord | ExecutionQuality]:
        """Alias for executions."""
        return self.executions

    @property
    def event_timeline(self) -> list[TradeEvent]:
        """Alias for events."""
        return self.events

    @property
    def sl_changes(self) -> list[TradeEvent]:
        """Events recording Stop Loss modifications."""
        target_types = {"SL_CHANGED", "STOP_LOSS_MODIFIED"}
        return [
            e for e in self.events
            if getattr(e.event_type, "value", str(e.event_type)) in target_types
        ]

    @property
    def tp_changes(self) -> list[TradeEvent]:
        """Events recording Take Profit modifications."""
        target_types = {"TP_CHANGED", "TAKE_PROFIT_MODIFIED"}
        return [
            e for e in self.events
            if getattr(e.event_type, "value", str(e.event_type)) in target_types
        ]

    @property
    def partial_closes(self) -> list[TradeEvent]:
        """Events recording partial scale-outs."""
        return [
            e for e in self.events
            if getattr(e.event_type, "value", str(e.event_type)) == "PARTIAL_CLOSE"
        ]

    @property
    def commission(self) -> float:
        return float(getattr(self.trade, "commission", 0.0) or 0.0)

    @property
    def swap(self) -> float:
        return float(getattr(self.trade, "swap", 0.0) or 0.0)

    @property
    def slippage_pips(self) -> float:
        if self.execution_quality is not None and hasattr(self.execution_quality, "slippage_pips"):
            return float(self.execution_quality.slippage_pips)
        if self.executions:
            return float(getattr(self.executions[0], "slippage_pips", 0.0) or 0.0)
        return 0.0

    @property
    def mfe(self) -> TradeMfeMae | None:
        return self.mfe_mae

    @property
    def mae(self) -> float:
        return float(self.mfe_mae.mae_pips if self.mfe_mae else 0.0)

    @property
    def realized_r(self) -> float:
        if self.trade.r_multiple is not None:
            return float(self.trade.r_multiple)
        if self.mfe_mae is not None:
            return float(self.mfe_mae.realized_r)
        return 0.0
