"""Domain Models for Forex Learning, Post-Trade Reflection & Lesson Retrieval (Phase 17).

Provides strongly-typed models for:
- ForexLesson: Granular, prescriptive heuristic derived from post-trade analysis.
- ReflectionRating & TradeReflection: Structured evaluation of trade execution discipline.
- RetrievedLesson: Lesson ranked by relevance score for dynamic prompt augmentation.
- ReflectionContext: Comprehensive context bundle supplied to the reflection agent.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field

from tradingagents.agents.schemas_forex import ForexTraderProposal
from tradingagents.database.models import (
    OrderExecutionRecord,
    ProposalRecord,
    TradeJournalRecord,
)
from tradingagents.journal.models import TradeEvent
from tradingagents.metrics.models import (
    ExecutionQuality,
    TradeMfeMae,
    TradeOutcomeResult,
)


class ReflectionRating(str, Enum):
    """Overall execution quality and behavioral grade for a trade."""

    EXCELLENT = "EXCELLENT"            # Exemplary adherence to strategy, optimal exit
    GOOD = "GOOD"                      # Controlled execution with solid risk containment
    NEUTRAL = "NEUTRAL"                # Scratch or routine trade with minimal learning signal
    POOR = "POOR"                      # Execution errors, greedy reversal, or premature exit
    CRITICAL_ERROR = "CRITICAL_ERROR"  # Hard rule breach, stop loss violation, or runaway loss


class ForexLesson(BaseModel):
    """Institutional heuristic or rule extracted from post-trade reflection."""

    lesson_id: str = Field(default_factory=lambda: f"lsn_{uuid.uuid4().hex[:12]}")
    trade_id: str | None = None
    proposal_id: str | None = None
    pair: str
    setup_type: str = "TREND_CONTINUATION"
    outcome_category: str = "STANDARD_WIN"
    rule_violated: str | None = None
    observation: str = ""
    root_cause: str = ""
    actionable_rule: str = ""
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0)
    tags: list[str] = Field(default_factory=list)
    created_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class RetrievedLesson(BaseModel):
    """A lesson retrieved from memory with an attached relevance score and diagnostic match reasons."""

    lesson: ForexLesson
    relevance_score: float = Field(default=1.0, ge=0.0, le=1.0)
    match_reasons: list[str] = Field(default_factory=list)


class TradeReflection(BaseModel):
    """Structured post-trade reflection report generated by ForexReflectionAgent."""

    trade_id: str
    rating: ReflectionRating = ReflectionRating.NEUTRAL
    summary: str = ""
    what_went_well: list[str] = Field(default_factory=list)
    what_went_wrong: list[str] = Field(default_factory=list)
    lessons: list[ForexLesson] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    generated_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class ReflectionContext(BaseModel):
    """Full operational context bundle supplied to the reflection engine."""

    trade: TradeJournalRecord
    proposal: ProposalRecord | ForexTraderProposal | None = None
    mfe_mae: TradeMfeMae | None = None
    outcome: TradeOutcomeResult | None = None
    executions: list[OrderExecutionRecord | ExecutionQuality] = Field(default_factory=list)
    events: list[TradeEvent] = Field(default_factory=list)
