"""Data models for SQLite trade journal, proposals, executions, and strategy versioning (Phase 12).

Provides typed representations for:
- ProposalRecord: Complete immutable record of ForexTraderProposal + ForexRiskDecision.
- TradeJournalRecord: Complete lifecycle representation of an executed Forex trade.
- OrderExecutionRecord: Broker fill/deal details (MT5 deals, execution slippage, spreads).
- StrategyVersionRecord: Tracking prompt version, model name, and strategy parameters.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from tradingagents.agents.schemas_forex import (
    ForexAction,
    ForexRiskDecision,
    ForexTraderProposal,
    OrderType,
    SetupType,
    sanitize_secrets,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class ProposalStatus(str, Enum):
    """Lifecycle status of a Forex trade proposal."""

    CREATED = "CREATED"             # Initialized proposal draft
    PROPOSED = "PROPOSED"           # Generated by ForexTrader agent
    APPROVED = "APPROVED"           # Cleared by ForexRiskEngine
    MODIFIED = "MODIFIED"           # Approved with mandatory adjustments
    REJECTED = "REJECTED"           # Denied by ForexRiskEngine
    RISK_REJECTED = "RISK_REJECTED" # Denied specifically by ForexRiskEngine
    WAITING_USER = "WAITING_USER"   # Awaiting trader review/action
    EXECUTED = "EXECUTED"           # Logged as executed (workflow intent or broker match)
    SKIPPED = "SKIPPED"             # Explicitly skipped by user
    SKIPPED_BY_USER = "SKIPPED_BY_USER" # Explicitly skipped by user (Phase 17)
    EXPIRED = "EXPIRED"             # Validity window lapsed without execution
    INVALIDATED = "INVALIDATED"     # Market structure / condition invalidated
    SUPERSEDED = "SUPERSEDED"       # Replaced by newer analysis for same pair
    CANCELLED = "CANCELLED"         # Manually or conditionally cancelled

    @classmethod
    def from_str(cls, val: Any) -> ProposalStatus:
        if isinstance(val, ProposalStatus):
            return val
        s = str(val).strip().upper()
        if s == "WAIT":
            return cls.WAITING_USER
        if s == "RISK_REJECTED":
            return cls.RISK_REJECTED
        if s == "SKIPPED_BY_USER":
            return cls.SKIPPED_BY_USER
        if s in ("SKIPPED", "SKIP"):
            return cls.SKIPPED
        for member in cls:
            if member.value == s or member.name == s:
                return member
        return cls.PROPOSED


class TradeStatus(str, Enum):
    """Lifecycle status of an active or settled trade."""

    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"

    @classmethod
    def from_str(cls, val: Any) -> TradeStatus:
        if isinstance(val, TradeStatus):
            return val
        s = str(val).strip().upper()
        for member in cls:
            if member.value == s:
                return member
        return cls.OPEN


class TradeExitReason(str, Enum):
    """Reason for closing an executed Forex position."""

    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    TRAILING_STOP = "TRAILING_STOP"
    MANUAL = "MANUAL"
    TIME_EXIT = "TIME_EXIT"
    NEWS_EVENT = "NEWS_EVENT"
    INVALIDATION = "INVALIDATION"
    AMBIGUOUS = "AMBIGUOUS"

    @classmethod
    def from_str(cls, val: Any) -> TradeExitReason | None:
        if val is None:
            return None
        if isinstance(val, TradeExitReason):
            return val
        s = str(val).strip().upper()
        if "AMBIGUOUS" in s:
            return cls.AMBIGUOUS
        for member in cls:
            if member.value == s:
                return member
        return cls.MANUAL


# ---------------------------------------------------------------------------
# Proposal Record Model
# ---------------------------------------------------------------------------


class ProposalRecord(BaseModel):
    """Persistent database representation of a ForexTraderProposal."""

    proposal_id: str = Field(default_factory=lambda: f"prop_{uuid.uuid4().hex[:12]}")
    created_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    pair: str
    action: ForexAction
    order_type: OrderType = OrderType.MARKET
    setup_type: SetupType = SetupType.TREND_CONTINUATION
    timeframe: str = "H1"
    entry_price: float | None = None
    entry_zone_low: float | None = None
    entry_zone_high: float | None = None
    stop_loss: float | None = None
    take_profit_1: float | None = None
    take_profit_2: float | None = None
    risk_reward_ratio: float | None = None
    sl_pips: float | None = None
    tp_pips: float | None = None
    confidence: float | None = None
    suggested_risk_percent: float | None = None
    suggested_lot_size: float | None = None
    confluence_factors: list[str] = Field(default_factory=list)
    invalidation_condition: str | None = None
    reasoning: str = ""
    trade_rationale_summary: str = ""
    status: ProposalStatus = ProposalStatus.PROPOSED
    risk_decision: dict[str, Any] | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    schema_version: int = 1
    run_id: str | None = None
    snapshot_id: str | None = None
    version_id: str | None = None
    proposal_payload: dict[str, Any] | None = None
    # Phase 23: Model / Prompt / Strategy Versioning
    provider: str | None = None
    quick_model: str | None = None
    deep_model: str | None = None
    temperature: float | None = None
    reasoning_effort: str | None = None
    max_tokens: int | None = None
    analysts: list[str] = Field(default_factory=list)
    prompt_version: str | None = None
    prompt_hash: str | None = None
    strategy_version: str = "1.0.0"
    system_version: str = "1.0.0"
    data_source_metadata: dict[str, Any] = Field(default_factory=dict)

    def to_forex_trader_proposal(self) -> ForexTraderProposal:
        """Construct domain ForexTraderProposal from database record."""
        if self.proposal_payload is not None:
            p = ForexTraderProposal.model_validate(self.proposal_payload)
            updates: dict[str, Any] = {}
            for f in (
                "provider", "quick_model", "deep_model", "temperature",
                "reasoning_effort", "max_tokens", "analysts", "prompt_version",
                "prompt_hash", "strategy_version", "system_version", "data_source_metadata"
            ):
                if getattr(p, f, None) is None and getattr(self, f, None) is not None:
                    updates[f] = getattr(self, f)
            if updates:
                p = p.model_copy(update=updates)
            return p
        return ForexTraderProposal(
            pair=self.pair,
            action=self.action,
            order_type=self.order_type,
            setup_type=self.setup_type,
            timeframe=self.timeframe,
            entry_price=self.entry_price,
            entry_zone_low=self.entry_zone_low,
            entry_zone_high=self.entry_zone_high,
            stop_loss=self.stop_loss,
            take_profit_1=self.take_profit_1,
            take_profit_2=self.take_profit_2,
            suggested_risk_percent=self.suggested_risk_percent,
            suggested_lot_size=self.suggested_lot_size,
            confluence_factors=self.confluence_factors,
            invalidation_condition=self.invalidation_condition,
            confidence=self.confidence,
            reasoning=self.reasoning,
            trade_rationale_summary=self.trade_rationale_summary,
            provider=self.provider,
            quick_model=self.quick_model,
            deep_model=self.deep_model,
            temperature=self.temperature,
            reasoning_effort=self.reasoning_effort,
            max_tokens=self.max_tokens,
            analysts=list(self.analysts),
            prompt_version=self.prompt_version,
            prompt_hash=self.prompt_hash,
            strategy_version=self.strategy_version,
            system_version=self.system_version,
            data_source_metadata=dict(self.data_source_metadata),
        )

    @property
    def valid_until(self) -> str | None:
        """ISO timestamp until which the trade proposal is valid."""
        if self.metadata:
            return self.metadata.get("valid_until_utc") or self.metadata.get("valid_until")
        return None

    @classmethod
    def from_forex_trader_proposal(
        cls,
        proposal: ForexTraderProposal,
        proposal_id: str | None = None,
        status: ProposalStatus = ProposalStatus.PROPOSED,
        risk_decision: ForexRiskDecision | dict[str, Any] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> ProposalRecord:
        """Create a ProposalRecord from a domain ForexTraderProposal."""
        pid = proposal_id or f"prop_{uuid.uuid4().hex[:12]}"
        rd_dict: dict[str, Any] | None = None
        if isinstance(risk_decision, ForexRiskDecision):
            rd_dict = risk_decision.model_dump()
        elif isinstance(risk_decision, dict):
            rd_dict = risk_decision

        meta = sanitize_secrets(dict(metadata or {}))
        clean_ds = sanitize_secrets(getattr(proposal, "data_source_metadata", {}) or {})
        if getattr(proposal, "valid_until", None) and "valid_until_utc" not in meta:
            meta["valid_until_utc"] = str(proposal.valid_until)

        # Store versioning in metadata for forward compatibility
        ver_meta = {
            "provider": getattr(proposal, "provider", None),
            "quick_model": getattr(proposal, "quick_model", None),
            "deep_model": getattr(proposal, "deep_model", None),
            "temperature": getattr(proposal, "temperature", None),
            "reasoning_effort": getattr(proposal, "reasoning_effort", None),
            "max_tokens": getattr(proposal, "max_tokens", None),
            "analysts": list(getattr(proposal, "analysts", []) or []),
            "prompt_version": getattr(proposal, "prompt_version", None),
            "prompt_hash": getattr(proposal, "prompt_hash", None),
            "strategy_version": getattr(proposal, "strategy_version", "1.0.0") or "1.0.0",
            "system_version": getattr(proposal, "system_version", "1.0.0") or "1.0.0",
            "data_source_metadata": clean_ds,
        }
        meta.setdefault("version_metadata", ver_meta)
        for vk, vv in ver_meta.items():
            if vv is not None and vk not in meta:
                meta[vk] = vv

        return cls(
            proposal_id=pid,
            proposal_payload=proposal.model_dump(mode="json"),
            pair=proposal.pair,
            action=proposal.action,
            order_type=proposal.order_type,
            setup_type=proposal.setup_type,
            timeframe=proposal.timeframe,
            entry_price=proposal.entry_price,
            entry_zone_low=proposal.entry_zone_low,
            entry_zone_high=proposal.entry_zone_high,
            stop_loss=proposal.stop_loss,
            take_profit_1=proposal.take_profit_1,
            take_profit_2=proposal.take_profit_2,
            risk_reward_ratio=proposal.risk_reward_ratio,
            sl_pips=proposal.sl_pips,
            tp_pips=proposal.tp_pips,
            suggested_risk_percent=proposal.suggested_risk_percent,
            suggested_lot_size=proposal.suggested_lot_size,
            confluence_factors=proposal.confluence_factors,
            invalidation_condition=proposal.invalidation_condition,
            confidence=getattr(proposal, "confidence", None) if getattr(proposal, "confidence", None) is not None else meta.get("confidence"),
            reasoning=proposal.reasoning,
            trade_rationale_summary=proposal.trade_rationale_summary,
            status=status,
            risk_decision=rd_dict,
            metadata=meta,
            provider=getattr(proposal, "provider", None),
            quick_model=getattr(proposal, "quick_model", None),
            deep_model=getattr(proposal, "deep_model", None),
            temperature=getattr(proposal, "temperature", None),
            reasoning_effort=getattr(proposal, "reasoning_effort", None),
            max_tokens=getattr(proposal, "max_tokens", None),
            analysts=list(getattr(proposal, "analysts", []) or []),
            prompt_version=getattr(proposal, "prompt_version", None),
            prompt_hash=getattr(proposal, "prompt_hash", None),
            strategy_version=getattr(proposal, "strategy_version", "1.0.0") or "1.0.0",
            system_version=getattr(proposal, "system_version", "1.0.0") or "1.0.0",
            data_source_metadata=clean_ds,
        )


# ---------------------------------------------------------------------------
# Trade Journal Record Model
# ---------------------------------------------------------------------------


class TradeJournalRecord(BaseModel):
    """Persistent representation of an executed trade in the Forex journal."""

    trade_id: str = Field(default_factory=lambda: f"trd_{uuid.uuid4().hex[:12]}")
    proposal_id: str | None = None
    pair: str
    action: ForexAction
    status: TradeStatus = TradeStatus.OPEN
    open_time_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    close_time_utc: str | None = None
    open_price: float
    close_price: float | None = None
    stop_loss: float
    take_profit: float | None = None
    lots: float
    commission: float = 0.0
    swap: float = 0.0
    gross_profit: float | None = None
    net_profit: float | None = None
    pips_gained: float | None = None
    r_multiple: float | None = None
    confidence: float | None = None
    exit_reason: TradeExitReason | None = None
    notes: str = ""
    reflection: str = ""
    tags: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def is_closed(self) -> bool:
        return self.status == TradeStatus.CLOSED

    @property
    def is_winner(self) -> bool:
        return self.net_profit is not None and self.net_profit > 0.0


# ---------------------------------------------------------------------------
# Order Execution Record Model
# ---------------------------------------------------------------------------


class OrderExecutionRecord(BaseModel):
    """Individual broker deal/execution fill event."""

    deal_id: str = Field(default_factory=lambda: f"deal_{uuid.uuid4().hex[:12]}")
    trade_id: str
    proposal_id: str | None = None
    pair: str
    order_type: str
    volume: float
    price: float
    slippage_pips: float = 0.0
    spread_at_open_pips: float = 0.0
    timestamp_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


# ---------------------------------------------------------------------------
# Strategy Version Record Model
# ---------------------------------------------------------------------------


class StrategyVersionRecord(BaseModel):
    """Metadata for tracking prompt version, LLM model, and strategy configuration."""

    version_id: str = Field(default_factory=lambda: f"v_{uuid.uuid4().hex[:8]}")
    strategy_name: str
    prompt_hash: str
    model_name: str
    parameters: dict[str, Any] = Field(default_factory=dict)
    created_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
