from typing import Annotated, Literal

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bearish Conversation history
    history: Annotated[str, "Conversation history"]  # Full debate history
    current_response: Annotated[str, "Latest response"]  # Latest response
    last_speaker: Annotated[Literal["bull", "bear", ""], "Researcher that spoke last (bull/bear)"]
    judge_decision: Annotated[str, "Final judge decision"]  # Final judge decision
    count: Annotated[int, "Length of the current conversation"]  # Conversation round count


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Aggressive Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conservative Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Neutral Conversation history
    history: Annotated[str, "Conversation history"]  # Full risk debate history
    latest_speaker: Annotated[Literal["Aggressive", "Conservative", "Neutral", ""], "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Latest aggressive response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Latest conservative response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Latest neutral response
    judge_decision: Annotated[str, "Judge's decision"]  # Final risk judge decision
    count: Annotated[int, "Length of the current conversation"]  # Conversation round count


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[Literal["stock", "crypto", "forex"], "Asset type under analysis such as stock, crypto, or forex"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    forex_technical_report: Annotated[str, "Report from the Forex Technical Analyst"]
    forex_macro_report: Annotated[str, "Report from the Forex Currency Macro Analyst"]
    forex_news_report: Annotated[str, "Report from the Forex Event/News Analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    portfolio_context: Annotated[str, "Caller-supplied holdings and cash, rendered at run start; empty when not provided"]
    forex_proposal: Annotated[dict | None, "Structured ForexTraderProposal data or serialized dict"]
    forex_risk_decision: Annotated[dict | None, "Structured ForexRiskDecision data or serialized dict"]
    forex_as_of_utc: Annotated[str, "Immutable UTC observation cutoff for Forex data"]
